[package]
name = "edi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
once_cell = "1.18"

[lib]
name = "edi_parser"
path = "src/lib.rs"

[[bin]]
name = "edi"
path = "src/main.rs"
